#!/bin/bash


APP_REPO=~/app-root/runtime/repo/
MODULES_REPO=$APP_REPO/connectors/

CRON_POSSIBILITIES=("--minutely" "--fiveminutely" "--hourly" "--daily")


isCronOption() 
{
	local e
	for e in "${CRON_POSSIBILITIES[@]}"; do
		if [[ "$1" == "$e" ]]; then
			return 1
		fi
	done
	return 0
}

createLogFile()
{
	if [[ ! -f $1 ]]; then
		mkdir -p $1
		rm -r $1
		touch $1
		echo "Log file $log was not existing, is now created"
	fi
}
